{application,reconnaissance,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{reconnaissance_app,[]}},
              {env,[]},
              {modules,[reconnaissance,reconnaissance_app,
                        reconnaissance_sup]}]}.
